### ISSUE TITLE
Menu option 3 do not work correctly

### ISSUE THREAD

**Issue by JoaoRodriguesRD** [JoaoRodriguesRD/dart_introduction#1]
Dont entry File method

**Comment by JoaoRodriguesRD** [comment]
- asynchronous ERROR - 
Quando seleciono a opção 3, ela volta para o menu, logo apos, se eu não digitar um numero do menu, ele retorna o item 3 normalmente... Estranho vou estudar mais...
```bash
Digite a questão que quer rodar: 1, 2, 3, 4, qualquer outro valor para finalizar a aplicação
s
Encerrando a aplicação
Digite o valor do salario mínimo: 
s
Unhandled exception:
FormatException: s
#0      num.parse (dart:core/num.dart:576:26)
#1      getNum (package:tarefa/tarefa.dart:43:14)
#2      questao03.<anonymous closure> (package:tarefa/tarefa.dart:51:25)
<asynchronous suspension>
joao@neto tarefa % dart run
Building package executable... 
Built tarefa:tarefa.
Olá!
Digite a questão que quer rodar: 1, 2, 3, 4, qualquer outro valor para finalizar a aplicação
3
questao 3 selecionada
Digite a questão que quer rodar: 1, 2, 3, 4, qualquer outro valor para finalizar a aplicação

Encerrando a aplicação
Digite o valor do salario mínimo: 
12
nome: joao rodrigues
Folha de pagamento: R$ 24 (2 salários mínimos)
nome: maria
Folha de pagamento: R$ 36 (3 salários mínimos)
nome: leandro
Folha de pagamento: R$ 96 (8 salários mínimos)
nome: adolfo
Folha de pagamento: R$ 120 (10 salários mínimos)
nome: edinaldo
Folha de pagamento: R$ 60 (5 salários mínimos)
joao@neto tarefa % 
```
